global_costmap:
    global_frame: odom   # (odom)
    robot_base_frame: base_link
    update_frequency: 5.0
    static_map: false
    rolling_window: false
    track_unknown_space: true

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}


