global_frame: odom
rolling_window: true
track_unknown_space: true

# obstacles_laser_g:
#     observation_sources: laser
#     laser: {sensor_frame: lidar_wamv_link, data_type: LaserScan, clearing: true, marking: false, topic: scan, inf_is_valid: true}

# obstacles_pc_g:
#     observation_sources: pointcloud
#     pointcloud: {sensor_frame: lidar_wamv_link, data_type: PointCloud2, clearing: false, marking: true, topic: /lidar_wamv/points_no_water}

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  # - {name: obstacles_pc,              type: "costmap_2d::VoxelLayer"}
  - {name: obstacles_pc,              type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
